export const items = [
  {
    id: Math.random(),
    title: "الإفطار",
    price: "50 درهم",
    desc: "فطار تركي: مشكل أجبان , مشكل مربي , خبز تركي , لبنة تركية ",
    category: "الإفطار",
    imgUrl: "breakfast.png",
  },
  {
    id: Math.random(),
    title: "الغداء",
    price: "120 درهم",
    desc: "مشاوي مشكلة",
    category: "الغداء",
    imgUrl: "lanch.jpg",
  },
  {
    id: Math.random(),
    title: "العشاء",
    price: "50 درهم",
    desc: "دجاج بالكاري",
    category: "العشاء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "الإفطار",
    price: "50 درهم",
    desc: "الإفطار تركي: مشكل أجبان , مشكل مربي , خبز تركي , لبنة تركية",
    category: "الإفطار",
    imgUrl: "breakfast.png",
  },
  {
    id: Math.random(),
    title: "الغداء",
    price: "50 درهم",
    desc: "دجاج بالكاري",
    category: "الغداء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "العشاء",
    price: "50 درهم",
    desc: "خفيف",
    category: "العشاء",
    imgUrl: "2.png",
  },

  {
    id: Math.random(),
    title: "الإفطار",
    price: "50 درهم",
    desc: "كيك",
    category: "الإفطار",
    imgUrl: "3.png",
  },
  {
    id: Math.random(),
    title: "الغداء",
    price: "120 درهم",
    desc: "مشاوي مشكلة",
    category: "الغداء",
    imgUrl: "lanch.jpg",
  },
  {
    id: Math.random(),
    title: "العشاء",
    price: "50 درهم",
    desc: "فطار تركي: مشكل أجبان , مشكل مربي , خبز تركي , لبنة تركية ",
    category: "العشاء",
    imgUrl: "1.png",
  },
  {
    id: Math.random(),
    title: "تصبيرة",
    price: "50 درهم",
    desc: "فطار تركي: مشكل أجبان , مشكل مربي , خبز تركي , لبنة تركية ",
    category: "تصبيرة",
    imgUrl: "1.png",
  },
];
